/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ece5580_apassi_crypto_LED */

#ifndef _Included_com_ece5580_apassi_crypto_LED
#define _Included_com_ece5580_apassi_crypto_LED
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ece5580_apassi_crypto_LED
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ece5580_apassi_crypto_LED_getMyString
  (JNIEnv *, jobject);

/*
 * Class:     com_ece5580_apassi_crypto_LED
 * Method:    encrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_ece5580_apassi_crypto_LED_encrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray);


#ifdef __cplusplus
}
#endif
#endif
